[package]
name = "bitcoin-address"
version = "0.1.0"
authors = ["Bogdan Arabadzhi <bogdan.today@gmail.com>"]
edition = "2018"

[dependencies]
bs58 = "0.3.0"
failure = "0.1.6"
secp256k1 = "0.17.2"
bitcoin_hashes = "0.7.4"
